export function generateHeader(): string {
  return `<h1 align="center">Hi <img src="public/webp/peepoHey.webp" alt="Hi" width="30" height="30" />, I'm Alexander Drazhev</h1>
<h3 align="center">A passionate software developer from Bulgaria</h3>
<p align="center">This page is auto generated by the repo itself</p>
`;
}
